name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'ra-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ra-backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        cd ra-backend
        cargo build --verbose

    - name: Run tests
      run: |
        cd ra-backend
        cargo test --verbose

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ra-backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ra-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 