name: NLP Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'nlp-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'nlp-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: nlp-service/requirements.txt

    - name: Install dependencies
      run: |
        cd nlp-service
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        cd nlp-service
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Type check with mypy
      run: |
        cd nlp-service
        pip install mypy
        mypy .

    - name: Run tests
      run: |
        cd nlp-service
        python -m pytest

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./nlp-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nlp-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 